=== cosimameyer/awesome-pyladies-creations/scripts/.chapter_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "name":      { "type": "string" },
    "city":      { "type": "string" },
    "country":   { "type": "string" },
    "email":     { "type": "string" },
    "website":   { "type": "string" },
    "photo_url": { "type": "string" },
    "lat": { "type": "number" },
    "lon": { "type": "number" },
    "social_media": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "x":         { "type": "string" },
          "facebook":  { "type": "string" },
          "github":    { "type": "string" },
          "linkedin":  { "type": "string" },
          "instagram": { "type": "string" },
          "meetup":    { "type": "string" },
          "mastodon":  { "type": "string" },
          "bluesky":   { "type": "string" },
          "youtube":   { "type": "string" },
          "website":   { "type": "string" }
        },
        "additionalProperties": false
      }
    }
  },
  "required": ["name", "city", "country"],
  "additionalProperties": false
}

=== cosimameyer/awesome-pyladies-creations/data/chapters/pyladies-arequipa-peru.json
{
  "name": "PyLadies Arequipa",
  "city": "Arequipa",
  "country": "Peru",
  "email": "aqp@pyladies.com",
  "photo_url": "https://pyladies.com/assets/images/pyladies_arequipa.jpg",
  "social_media": [
    {
      "github": "https://github.com/PyladiesAqp",
      "facebook": "https://facebook.com/@aqp.pyladies"
    }
  ]
}

=== cosimameyer/awesome-pyladies-creations/data/chapters/pyladies-salvador-brazil.json
{
  "name": "PyLadies Salvador",
  "city": "Salvador",
  "country": "Brazil",
  "email": "salvador@pyladies.com",
  "website": "https://pyladiessalvador.github.io/",
  "social_media": [
    {
      "github": "https://github.com/PyLadiesSalvador",
      "facebook": "https://facebook.com/PyLadiesSalvador"
    }
  ]
}

=== cosimameyer/awesome-pyladies-creations/data/chapters/pyladies-toronto-canada.json
{
  "name": "PyLadies Toronto",
  "city": "Toronto",
  "country": "Canada",
  "email": "toronto@pyladies.com",
  "social_media": [
    {
      "meetup": "Pyladies-Toronto",
      "instagram": "pyladiestoronto",
      "facebook": "pyladiestoronto",
      "github": "pyladiestoronto"
    }
  ],
  "website": "https://pyladiestoronto.github.io",
  "lat": 43.6534817,
  "lon": -79.3839347
}

=== cosimameyer/awesome-pyladies-creations/data/chapters/pyladies-indonesia.json
{
  "name": "PyLadies Indonesia",
  "city": "Various",
  "country": "Indonesia",
  "email": "indonesia@pyladies.com",
  "photo_url": "https://pyladies.com/assets/images/pyladies_indonesia.png",
  "social_media": [
    {
      "x": "PyLadiesID",
      "linkedin": "company/pyladies-indonesia",
      "instagram": "pyladiesid",
      "github": "PyLadiesID"
    }
  ],
  "lat": -2.4833826,
  "lon": 117.8902853
}

=== cosimameyer/awesome-pyladies-creations/data/chapters/pyladies-bratislava-slovakia.json
{
  "name": "PyLadies Bratislava",
  "city": "Bratislava",
  "country": "Slovakia",
  "email": "bratislava@pyladies.org",
  "photo_url": "https://pyladies.com/assets/images/pyladies_logo.png",
  "social_media": [
    {
      "facebook": "PyLadiesBratislava",
      "github": "pyladies-bratislava"
    }
  ],
  "website": "https://bratislava.pyladies.com",
  "lat": 48.1516988,
  "lon": 17.1093063
}

=== cosimameyer/awesome-pyladies-creations/data/chapters/pyladies-south-florida-usa.json
{
  "name": "PyLadies South Florida",
  "city": "South Florida",
  "country": "USA",
  "email": "southflorida@pyladies.com",
  "social_media": [
    {
      "github": "PyLadiesSoFlo",
      "x": "PyLadiesSoFlo",
      "facebook": "PyLadiesSoFlo",
      "meetup": "PyLadies-SoFlo"
    }
  ],
  "lat": 37.1670484,
  "lon": -94.8463851
}

=== cosimameyer/awesome-pyladies-creations/data/chapters/pyladies-saint-petersburg-russia.json
{
  "name": "PyLadies Saint Petersburg",
  "city": "Saint Petersburg",
  "country": "Russia",
  "email": "spb@pyladies.com",
  "website": "http://spb.pyladies.com",
  "social_media": [
    {
      "x": "pyladies_spb",
      "facebook": "pyladies.spb",
      "github": "pyladies-spb"
    }
  ],
  "lat": 59.9606739,
  "lon": 30.1586551
}

=== cosimameyer/awesome-pyladies-creations/data/chapters/pyladies-sorocaba-sp.json
{
  "name": "PyLadies Sorocaba",
  "city": "Sorocaba",
  "country": "Brazil",
  "email": "sorocaba@pyladies.com",
  "social_media": [
    {
      "facebook": "PyLadiesSorocaba",
      "youtube": "sorocabapyladies9240",
      "github": "PyLadiesSorocaba"
    }
  ],
  "lat": -23.5003451,
  "lon": -47.4582864
}
