=== cosimameyer/awesome-pyladies-creations/scripts/.entry_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "title": {"type": "string"},
    "url":   {"type": "string"},
    "rss_feed": {"type": "string"},
    "type":  {
      "type": "string",
      "enum": ["blog", "youtube", "podcast"]
    },
    "photo_url":   {"type": "string"},
    "description": {"type": "string"},
    "language":    {"type": "string"},
    "authors": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "name": {"type": "string"},
            "social_media": {
              "type": "array",
              "items": [
                {
                  "type": "object",
                  "properties": {
                    "x":            {"type": "string"},
                    "mastodon":     {"type": "string"},
                    "bluesky":      {"type": "string"},
                    "linkedin":     {"type": "string"},
                    "facebook":     {"type": "string"},
                    "github":       {"type": "string"},
                    "instagram":    {"type": "string"},
                    "youtube":      {"type": "string"},
                    "tiktok":       {"type": "string"},
                    "periscope":    {"type": "string"},
                    "researchgate": {"type": "string"},
                    "website":      {"type": "string"},
                    "orcid":        {"type": "string"},
                    "meetup":       {"type": "string"}
                  }
                }
              ]
            }
          },
          "required": [
            "name"
          ]
        }
      ]
    }
  },
  "required": [
    "title",
    "url",
    "type",
    "photo_url",
    "authors",
    "language"
  ]
}

=== cosimameyer/awesome-pyladies-creations/data/content/whykay-dev.to.json
{
  "title": "whykay @ dev.to",
  "type": "blog",
  "url": "https://dev.to/whykay",
  "photo_url": "https://media.licdn.com/dms/image/D4E03AQG3lcPFRvoCLA/profile-displayphoto-shrink_800_800/0/1671633150179?e=2147483647&v=beta&t=PIBSiQwOS4UE9OQ31JLrmWUoMEk8a4xSo3cUmiPaxg8",
  "language": "en", 
  "rss_feed": "https://dev.to/feed/whykay", 
  "authors": [ 
    {
      "name": "Vicky Twomey-Lee",
      "social_media": [{
         "twitter": "whykay",
         "mastodon": "@whykay@mastodon.ie",
         "github": "whykay",
         "instagram": "theycallmejanie",
         "website": "https://beacons.page/whykay",
         "linkedin": "vickyleeire",
         "bluesky": "@whykay.bsky.social"
      }]
    }
  ]
}

=== cosimameyer/awesome-pyladies-creations/data/content/foosel.net.json
{
  "title": "foosel.net",
  "type": "blog",
  "url": "https://foosel.net",
  "photo_url": "https://foosel.net/img/me.jpg",
  "language": "en",
  "rss_feed": "https://foosel.net/tags/python/index.xml",
  "description": "Python, OctoPrint development, maker projects, TIL posts, and technical deep-dives",
  "authors": [
    {
      "name": "Gina Häßge",
      "social_media": [{
        "github": "foosel",
        "mastodon": "@foosel@chaos.social",
        "bluesky": "@foosel.net",
        "linkedin": "ginahaeussge",
        "website": "https://foosel.net"
      }]
    }
  ]
}

=== cosimameyer/awesome-pyladies-creations/data/content/isabelizimm.github.io.json
{
  "title": "Isabel Zimmerman",
  "type": "blog",
  "url": "https://isabelizimm.github.io/",
  "rss_feed": "https://isabelizimm.github.io/blog-python.xml",
  "photo_url": "https://avatars.githubusercontent.com/u/54685329?v=4",
  "language": "en",
  "authors": [ 
    {
      "name": "Isabel Zimmerman",
      "social_media": [{
         "x": "@isabelizimm",
         "mastodon": "@isabelizimm@fosstodon.org",
         "github": "isabelizimm",
         "linkedin": "isabel-zimmerman",
         "bluesky": "@isabelizimm.bsky.social"
      }]
    }
  ]
}

=== cosimameyer/awesome-pyladies-creations/data/content/youtube.com.@SophiaYangDS.json
{
  "title": "Sophia Yang",
  "type": "youtube",
  "url": "https://www.youtube.com/@SophiaYangDS",
  "photo_url": "https://github.com/sophiamyang.png",
  "rss_feed": "https://www.youtube.com/feeds/videos.xml?channel_id=UC-1K1KRfh-2d0ckHyAa82eA",
  "language": "en",
  "authors": [
    {
      "name": "Sophia Yang",
      "social_media": [{
        "github": "sophiamyang"
      }]
    }
  ]
}

=== cosimameyer/awesome-pyladies-creations/data/content/jessica0greene-medium.json
{
  "title": "Jessica Greene (PyLadies Berlin) Medium account",
  "type": "blog",
  "url": "https://medium.com/@jessica0greene",
  "photo_url": "https://miro.medium.com/v2/resize:fill:96:96/1*vp3dQ60qsoukSFGws6dNlg.jpeg",
  "rss_feed": "https://medium.com/feed/@jessica0greene",
  "language": "en",
  "authors": [
    {
      "name": "Jessica Greene",
      "social_media": [{
        "x": "sleepypioneer",
        "mastodon": "@sleepypioneer@mastodon.social",
        "github": "sleepypioneer",
        "website": "http://onlinegurl.co.uk",
        "linkedin": "jessica0greene/"
      }]
    }
  ]
}

=== cosimameyer/awesome-pyladies-creations/data/content/blog.isabel-drost.de.json
{
  "title": "Inductive Bias",
  "type": "blog",
  "url": "https://blog.isabel-drost.de/",
  "photo_url": "https://avatars.githubusercontent.com/u/70953?v=4",
  "language": "en",
  "description": "Open source governance, InnerSource, Open Source projects e.g. at The ASF, and machine learning",
  "authors": [
    {
      "name": "Isabel Drost-Fromm",
      "social_media": [{
        "github": "MaineC",
        "linkedin": "isabel-drost-fromm-2a064a2",
        "website": "https://isabel-drost.de/"
      }]
    }
  ]
}

=== cosimameyer/awesome-pyladies-creations/data/content/nnja.io.json
{
  "title": "Nina Zakharenko",
  "type": "blog",
  "url": "https://www.nnja.io/",
  "photo_url": "https://www.nnja.io/me.jpg",
  "language": "en",
  "rss_feed": "https://www.nnja.io/tags/python/index.xml",
  "description": "Python, CircuitPython, hardware projects, and developer conference talks",
  "authors": [
    {
      "name": "Nina Zakharenko",
      "social_media": [{
        "github": "nnja",
        "x": "nnja",
        "mastodon": "@nnja@mastodon.social",
        "bluesky": "@nnja.bsky.social",
        "linkedin": "nnja",
        "website": "https://www.nnja.io"
      }]
    }
  ]
}

=== cosimameyer/awesome-pyladies-creations/data/content/youtube.com.@cheuktingho.json
{
  "title": "Cheuk Ting Ho",
  "type": "youtube",
  "url": "https://www.youtube.com/@cheuktingho",
  "photo_url": "https://github.com/Cheukting.png",
  "rss_feed": "https://www.youtube.com/feeds/videos.xml?channel_id=UCs0-1JQdb1YkVxN4hnNKsNQ",
  "language": "en",
  "authors": [
    {
      "name": "Cheuk Ting Ho",
      "social_media": [{
        "github": "Cheukting",
        "x": "cheukting_ho"
      }]
    }
  ]
}
