=== cosimameyer/awesome-pyladies-creations/scripts/.entry_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "title": {"type": "string"},
    "url":   {"type": "string"},
    "rss_feed": {"type": "string"},
    "type":  {
      "type": "string",
      "enum": ["blog", "youtube", "podcast"]
    },
    "photo_url":   {"type": "string"},
    "description": {"type": "string"},
    "language":    {"type": "string"},
    "authors": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "name": {"type": "string"},
            "social_media": {
              "type": "array",
              "items": [
                {
                  "type": "object",
                  "properties": {
                    "x":            {"type": "string"},
                    "mastodon":     {"type": "string"},
                    "bluesky":      {"type": "string"},
                    "linkedin":     {"type": "string"},
                    "facebook":     {"type": "string"},
                    "github":       {"type": "string"},
                    "instagram":    {"type": "string"},
                    "youtube":      {"type": "string"},
                    "tiktok":       {"type": "string"},
                    "periscope":    {"type": "string"},
                    "researchgate": {"type": "string"},
                    "website":      {"type": "string"},
                    "orcid":        {"type": "string"},
                    "meetup":       {"type": "string"}
                  }
                }
              ]
            }
          },
          "required": [
            "name"
          ]
        }
      ]
    }
  },
  "required": [
    "title",
    "url",
    "type",
    "photo_url",
    "authors",
    "language"
  ]
}

=== cosimameyer/awesome-pyladies-creations/data/content/ines.io.json
{
  "title": "Ines Montani",
  "type": "blog",
  "url": "https://ines.io",
  "rss_feed": "https://ines.io/feed",
  "photo_url": "https://ines.io/static/31a698b834e1e4b6f7d15b9b306a9439/e9e8b/profile.jpg",
  "language": "en",
  "authors": [
    {
      "name": "Ines Montani",
      "social_media": [
        {
          "x": "@_inesmontani",
          "mastodon": "@ines@sigmoid.social",
          "github": "ines",
          "website": "https://ines.io",
          "linkedin": "inesmontani/"
        }
      ]
    }
  ]
}

=== cosimameyer/awesome-pyladies-creations/data/content/monika.ai.json
{
  "title": "Monika Venčkauskaitė",
  "type": "blog",
  "url": "https://monika.ai",
  "photo_url": "https://avatars.githubusercontent.com/u/18329988?v=4",
  "language": "en",
  "description": "MLOps platform implementation, machine learning operations, and web development",
  "authors": [
    {
      "name": "Monika Venčkauskaitė",
      "social_media": [{
        "github": "MonikaVen",
        "x": "MonikaVenck",
        "linkedin": "monika-in-ml",
        "website": "https://monika.ai"
      }]
    }
  ]
}

=== cosimameyer/awesome-pyladies-creations/data/content/emilyemorehouse.com.json
{
  "title": "Emily Morehouse",
  "type": "blog",
  "url": "https://emilyemorehouse.com",
  "photo_url": "https://github.com/emilyemorehouse.png",
  "language": "en",
  "authors": [
    {
      "name": "Emily Morehouse",
      "social_media": [{
        "github": "emilyemorehouse",
        "x": "emilyemorehouse",
        "linkedin": "emily-morehouse-10567459",
        "instagram": "emilycodes"
      }]
    }
  ]
}

=== cosimameyer/awesome-pyladies-creations/data/content/emilyriederer.com.json
{
  "title": "Emily Riederer", 
  "type": "blog", 
  "url": "https://emilyriederer.com", 
  "photo_url": "https://avatars.githubusercontent.com/u/19798371",
  "description": "Thoughts on advancing the data analysis lifecycle -- from data quality and management, reproducible tooling, and statistical methods",
  "language": "en", 
  "rss_feed": "https://www.emilyriederer.com/tags/python/index.xml", 
  "authors": [ 
    {
      "name": "Emily Riederer", 
      "social_media": [{
         "x": "emilyriederer",
         "mastodon": "@emilyriederer@mastodon.social",
         "github": "emilyriederer",
         "website": "emilyriederer.com",
         "linkedin": "emilyriederer/",
         "facebook": "emilyriederer",
         "orcid": "0000-0002-1788-7934",
         "bluesky": "@emilyriederer.bsky.social"
      }]
    }
  ]
}

=== cosimameyer/awesome-pyladies-creations/data/content/pyladies-paris.json
{
  "title": "Pyladies Paris",
  "type": "youtube",
  "url": "https://www.youtube.com/channel/UCVa3pfqJDQgce6YYrpKnIjg",
  "photo_url": "https://pyladies.com/assets/images/pyladies_dc_atl_sea_tor.png",
  "language": "fr",
  "rss_feed": "https://www.youtube.com/feeds/videos.xml?channel_id=UCVa3pfqJDQgce6YYrpKnIjg",
  "authors": [
    {
      "name": "Pyladies Paris",
      "social_media": [
        {
          "x": "https://twitter.com/PyLadiesParis",
          "meetup": "https://www.meetup.com/PyLadies-Paris/",
          "youtube": "https://www.youtube.com/channel/UCVa3pfqJDQgce6YYrpKnIjg"
        }
      ]
    }
  ]
}

=== cosimameyer/awesome-pyladies-creations/data/content/welearncode.com.json
{
  "title": "Ali Spittel",
  "type": "blog",
  "url": "https://welearncode.com",
  "photo_url": "https://github.com/aspittel.png",
  "rss_feed": "https://welearncode.com/rss.xml",
  "language": "en",
  "authors": [
    {
      "name": "Ali Spittel",
      "social_media": [{
        "github": "aspittel",
        "x": "aspittel",
        "instagram": "ali_writes_code"
      }]
    }
  ]
}

=== cosimameyer/awesome-pyladies-creations/data/content/rsip22.github.io.json
{
  "title": "Renata Davila",
  "type": "blog",
  "url": "https://rsip22.github.io/blog/",
  "photo_url": "https://github.com/rsip22.png",
  "rss_feed": "https://rsip22.github.io/blog/feeds/all.atom.xml",
  "language": "en",
  "authors": [
    {
      "name": "Renata Davila",
      "social_media": [{
        "github": "rsip22",
        "x": "rsip22",
        "linkedin": "rsip22"
      }]
    }
  ]
}

=== cosimameyer/awesome-pyladies-creations/data/content/blog.djangogirls.org.json
{
  "title": "Django Girls Blog",
  "type": "blog",
  "url": "https://blog.djangogirls.org",
  "photo_url": "https://github.com/DjangoGirls.png",
  "rss_feed": "https://blog.djangogirls.org/rss",
  "language": "en",
  "authors": [
    {
      "name": "Django Girls",
      "social_media": [{
        "github": "DjangoGirls",
        "x": "djangogirls"
      }]
    }
  ]
}
